url: http://solitude.vkps.co.uk
name: Solitude
lsi: false
description: >
  Technology. Code. Living relentlessly in
  the real world.
timezone: Europe/London
encoding: utf-8

baseurl: /solitude-jekyll

permalinks: /:year/:month/:title

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, docs]

paginate: 5
paginate_path: "/page/:num"

gems: [ "jekyll-archives", "jekyll-paginate", "jekyll-twitter-plugin"]
# plugins: ['jekyll-twitter-plugin']

jekyll-archives:
  enabled: ["all", "year", "month"]
  layout: 'archive'
  permalinks:
    year: '/Archives/:year/'
    month: '/Archives/:year/:month/'
