url: http://solitude.vkps.co.uk
name: Solitude
description: >
  Technology. Code. Living relentlessly in
  the real world.
timezone: Europe/London
encoding: utf-8

paginate: 5
paginate_path: "/page/:num"

gems: [ "jekyll-archives", "jekyll-paginate"]

jekyll-archives:
  enabled:
    - year
    - month
    - tag
  layout: 'default'
  permalinks:
    year: '/Archives/:year/'
    month: '/Archives/:year/:month/'
    tag: '/tag/:name/'
    