url: "https://solitude.vkps.co.uk"
name: Solitude
lsi: false
description: >
  Technology. Code. Living relentlessly in
  the real world.
timezone: Europe/London
encoding: utf-8

baseurl: ""

permalinks: /:year/:month/:title

exclude: [LICENSE, README.md, .gitignore, Gemfile, _local.yml, local-serve.sh, Gemfile.lock, docs, gh-generate.sh]

paginate: 5
paginate_path: "/page/:num"

plugins: [ "jekyll-archives", "jekyll-paginate", "jekyll-twitter-plugin"]


jekyll-archives:
  enabled: ["all", "year", "month"]
  layout: 'archive'
  permalinks:
    year: '/Archives/:year/'
    month: '/Archives/:year/:month/'
